# Generated by Django 4.1.5 on 2023-01-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_alter_band_formed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='formed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
