# Generated by Django 4.1.5 on 2023-01-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_alter_band_approved_alter_band_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
