# Generated by Django 4.1.5 on 2023-01-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
