# Generated by Django 4.1.5 on 2023-01-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_alter_band_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='band',
            name='formed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
