# Generated by Django 4.1.6 on 2023-02-01 18:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_alter_band_approved_alter_band_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='news',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
