# Generated by Django 4.1.6 on 2023-02-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0011_remove_news_text_news_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='notes',
            new_name='text',
        ),
    ]
