# Generated by Django 4.1.6 on 2023-02-01 22:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0012_rename_notes_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='images',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
