# Generated by Django 4.1.6 on 2023-02-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0013_band_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='images',
        ),
    ]
