# Generated by Django 4.1.6 on 2023-02-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0014_remove_band_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
