# Generated by Django 4.1.6 on 2023-02-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0016_remove_band_user_id_band_favourites_band_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='favourites',
        ),
    ]
