# Generated by Django 4.1.6 on 2023-02-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0018_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
